---
 - name: Deploy comparev3 app to Docker container
   hosts: dockerC
   become: yes
   
   tasks:
     
    - name: Copy JAR file to remote host
      copy:
        src=target/myapp.jar
        dest=/opt/myapp/myapp.jar
        mode=0755

    - name: Copy Dockerfile
      copy:
        src=Dockerfile
        dest=/opt/myapp/Dockerfile

    - name: Build Docker Image
      docker_image:
        path: /opt/myapp
        name: my-java-app
        tag: latest
        state: present

    - name: Run Docker Container
      docker_container:
        name: my-java-app
        image: my-java-app:latest
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
