---
- name: Deploy comparev3 app to Docker container
  hosts: dockerC
  become: yes

  tasks:

    - name: Ensure target directory exists
      file:
        path: /opt/myapp
        state: directory
        mode: '0755'

    - name: Copy JAR file to remote host
      copy:
        src: /var/lib/jenkins/workspace/comparev3/target/numeric-0.0.1.jar
        dest: /opt/myapp/numeric-0.0.1.jar
        mode: '0755'

    - name: Copy Dockerfile to remote host
      copy:
        src: /var/lib/jenkins/workspace/comparev3/Dockerfile
        dest: /opt/myapp/Dockerfile
        mode: '0644'

    - name: Build Docker Image
      docker_image:
        path: /opt/myapp
        name: java-app
        tag: latest
        state: present

    - name: Run Docker Container
      docker_container:
        name: java-app
        image: java-app:latest
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
